### ISSUE TITLE
因为是基于appium 如果希望支持IOS 在目前android的版本上该如何改进呢？谢谢

### ISSUE THREAD

**Issue by oatsuper** [zippies/mirror#1]

**Comment by zippies** [comment]
现在我还没搞IOS的自动化，等哪天要做了再更新一个IOS的版本吧~现在获取包名，启动activity用的是android的aapt，IOS的话应该有一套获取这些东西的工具，具体问题我现在还不确定，以后做IOS的或者有时间了再看吧

**Comment by oatsuper** [comment]
嗯，谢谢
